name: BambossSMP
main: net.boster.bamboss.smp.BambossSMP
author: Bosternike
version: 1.0.0
api-version: 1.13
softdepend: [PlaceholderAPI]
depend: [Multiverse-Core, Multiverse-NetherPortals, BambossCoins, BosterChat]